name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xmllint
      run:  sudo apt-get -y install libgtest-dev
    - name: make
      run: make -f Makefile
    - name: make check
      run: ./TestKDTree
