name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: AdrianGarciaB/proyectoAlgoritmia2023@v1
    - name: make
      run: cd ../../ && make -f Makefile
    - name: make check
      run: ./TestKDTree
